name: catbox
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.1.0"
  firebase_auth: "0.5.3"
  google_sign_in: "3.0.0"
  cloud_firestore: "0.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts: 
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-MediumItalic.ttf
        - asset: fonts/Ubuntu-Regular.ttf
    
  assets:
    - assets/cats.json
    - images/profile_header_background.png
